// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdJGv-DqkpTK407mKIVmi-dGozkHkHjQs',
    appId: '1:999485288786:web:c8c7983962f74d95da0a8b',
    messagingSenderId: '999485288786',
    projectId: 'log-b-4de05',
    authDomain: 'log-b-4de05.firebaseapp.com',
    storageBucket: 'log-b-4de05.firebasestorage.app',
    measurementId: 'G-K0PW8QEDND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDASA4-ixldgAkUHfGhHXg496AKV-Cch0s',
    appId: '1:999485288786:android:3e741616993518dbda0a8b',
    messagingSenderId: '999485288786',
    projectId: 'log-b-4de05',
    storageBucket: 'log-b-4de05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYbJII3H12xvvR1TbR5VaQwbkdJeOaOJs',
    appId: '1:999485288786:ios:81b00201990999b9da0a8b',
    messagingSenderId: '999485288786',
    projectId: 'log-b-4de05',
    storageBucket: 'log-b-4de05.firebasestorage.app',
    iosClientId: '999485288786-091bcmbahka266v922770h13isoe7fje.apps.googleusercontent.com',
    iosBundleId: 'com.logb.logb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYbJII3H12xvvR1TbR5VaQwbkdJeOaOJs',
    appId: '1:999485288786:ios:81b00201990999b9da0a8b',
    messagingSenderId: '999485288786',
    projectId: 'log-b-4de05',
    storageBucket: 'log-b-4de05.firebasestorage.app',
    iosClientId: '999485288786-091bcmbahka266v922770h13isoe7fje.apps.googleusercontent.com',
    iosBundleId: 'com.logb.logb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdJGv-DqkpTK407mKIVmi-dGozkHkHjQs',
    appId: '1:999485288786:web:2f12c38eddccabb4da0a8b',
    messagingSenderId: '999485288786',
    projectId: 'log-b-4de05',
    authDomain: 'log-b-4de05.firebaseapp.com',
    storageBucket: 'log-b-4de05.firebasestorage.app',
    measurementId: 'G-LN4NYEGZ6M',
  );
}
